### ISSUE TITLE
2019c_M15

### ISSUE THREAD

**Issue by micheledoro** [andreatramacere/magic-backend#6]
I have written up the information of the third paper in 2019 (2019c), I have:
- called the directory 2019c_m15, is that bad?
- used the semicolon in the .ecsv file;
- used the 'data format' field
I have only to convert the nufnu which is in erg/s and then this file should be ready to check

**Comment by andreatramacere** [comment]
OK,
I just need to know if the catalog file will have the same name of the directory or not.

**Comment by micheledoro** [comment]
The idea is to have all file of this paper with the format 'magic_2019c_xxx' so indeed, the tag '2019c' is in the folder name

**Comment by andreatramacere** [comment]
OK, just to be sure,  case 1 or 2 ?

1.
```
MAGIC_data/data/2019c_m15/
├── magic_2019c.yaml
├── magic_2019c_sed_fig1.ecsv
```

2.
```
MAGIC_data/data/2019c_m15/
├── magic_2019c_m15.yaml
├── magic_2019c_m15_sed_fig1.ecsv
```

**Comment by micheledoro** [comment]
The right one is 
```
MAGIC_data/data/2019c_m15/
├── magic_2019c_m15.yaml
├── magic_2019c_m15_fig1_sed.ecsv
```

**Comment by micheledoro** [comment]
That file is completed. I can close this issue.
